### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by mmmenno** [nypl-spacetime/Leaflet.GeotagPhoto#12] opened 2017-03-09 09:17 UTC
In Leiden, a stunning 20% of the website visitors are using Internet Explorer 11 instead of a browser. These people don't see anything (no camera or target icons, map-to-camera-and-vv-icons) - see attached screendump. Do you think this is something that could easily be fixed? 

![image](https://cloud.githubusercontent.com/assets/4539618/23743618/a00febd4-04b1-11e7-9c3e-eded6264d0ee.png)

**Comment by bertspaan** [comment] 2017-03-09 12:38
Yes, I think so. However, I don't have IE so I cannot test or fix it easily myself. Can you try to see what the problem is? Errors in console? Weird placement of markers?

**Comment by erfgoedleiden** [comment] 2017-03-09 15:56
I guess it's a HTTPS-issue :)
I've tried it on two different computers, and they both give the same errors:

<img width="676" alt="schermafbeelding 2017-03-09 om 16 52 53" src="https://cloud.githubusercontent.com/assets/13898887/23758118/fcc342f4-04e8-11e7-811a-e7ea131fcad8.png">
<img width="925" alt="schermafbeelding 2017-03-09 om 16 53 18" src="https://cloud.githubusercontent.com/assets/13898887/23758119/fcc48d94-04e8-11e7-8b41-fd4d174b7351.png">

**Comment by bertspaan** [comment] 2017-03-09 17:21
But that would not cause the camera + target to not be there.

This would:

![image](https://cloud.githubusercontent.com/assets/1194896/23762039/dbf42014-04c2-11e7-81c5-4f89ca4fcb6b.png)

**Comment by bertspaan** [comment] 2017-03-09 17:32
@mmmenno published new version 0.3.4 - does it work now?

**Comment by bertspaan** [comment] 2017-03-09 17:33
I think that the HTTPS issue is caused by the face that your website is served using HTTPS, but the tiles are using standard HTTP. This is not related to Leaflet.GeotagPhoto.

**Comment by mmmenno** [comment] 2017-03-10 07:41
@erfgoedleiden If you are near an IE11 browser, could you check if it's working now?

**Comment by erfgoedleiden** [comment] 2017-03-10 17:55
http://spacetime.nypl.org/Leaflet.GeotagPhoto/examples/camera.html gives the same result
![virtualbox_windows_7_10_03_2017_18_49_48](https://cloud.githubusercontent.com/assets/13898887/23806605/97e56616-05c2-11e7-84d0-c50a36fa19ca.png)

Console:
SCRIPT438: Object doesn't support property or method 'assign'
File: Leaflet.GeotagPhoto.min.js, Line: 1, Column: 5269

**Comment by bertspaan** [comment] 2017-03-10 17:59
Ah! I fixed only half of the problem! Wait, new version is coming!

**Comment by phpetra** [comment] 2017-03-10 18:01
@erfgoedleiden Have you by any change also cleared the browser cache?

**Comment by bertspaan** [comment] 2017-03-10 18:04
New version! Does it work now?

**Comment by erfgoedleiden** [comment] 2017-03-10 18:15
<img width="1140" alt="schermafbeelding 2017-03-10 om 19 13 43" src="https://cloud.githubusercontent.com/assets/13898887/23807386/d826b68c-05c5-11e7-948d-bfff6948d83a.png">

Console:
SCRIPT438: Object doesn't support property or method 'includes'
File: Leaflet.GeotagPhoto.min.js, Line: 1, Column: 13889

**Comment by bertspaan** [comment] 2017-03-10 23:39
We'll get there! Can you try again?

**Comment by erfgoedleiden** [comment] 2017-03-11 06:38
The camera is working! 
<img width="1172" alt="schermafbeelding 2017-03-11 om 07 37 03" src="https://cloud.githubusercontent.com/assets/13898887/23821282/a0ea8546-062d-11e7-81a3-67310fe83298.png">
It is however not possible to adjust the angle.

**Comment by bertspaan** [comment] 2017-03-11 12:37
Any errors when you move the slider?

**Comment by bertspaan** [comment] 2017-03-11 12:40
Oh, I think [this](http://stackoverflow.com/questions/28118849/range-slider-input-event-not-firing-in-ie-10) is the problem!

**Comment by bertspaan** [comment] 2017-03-11 12:50
I've updated example - can you try again?

**Comment by erfgoedleiden** [comment] 2017-03-12 06:38
Everything works perfectly 👍

**Closed** 2017-03-12 14:37 UTC

**Comment by phpetra** [comment] 2017-03-13 09:23
Quick fix, Bert. Thanks!
